version: '3.8'

services:
  # Servicio de la aplicación PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - todolist-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: todolist-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - todolist-network

  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: todolist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge

volumes:
  dbdata: 